#!/usr/bin/env bash
# Optional FederLoom installer for the Mailcow-Crowdsec-Override integration.
#
# Runs locally on the Mailcow host. Generates the dynamic config (config.local.yaml
# and the federloom compose service — with detected IPs, CrowdSec API key, and
# advertise address), fetches the static upstream files (rules.yaml,
# federation.invite), registers a CrowdSec bouncer, merges the service into the
# existing docker-compose.override.yml (backup + validate + restore on failure),
# starts FederLoom, and offers an opt-in federation join.
#
# Idempotent. Never modifies Mailcow-owned files.
set -euo pipefail

FEDERLOOM_REPO="https://github.com/JoeRu/federloom"
FINGERPRINT="79bb d13a 114b 88fe"
DEFAULT_MAILCOW_ROOT="/opt/mailcow-dockerized"
ASSUME_YES=0
MAILCOW_ROOT=""
CROWDSEC_CTR=""
POSTFIX_CTR=""
DOVECOT_CTR=""
PUBLIC_IP=""
TAILSCALE_IP=""
MAILCOW_NETWORK="172.22.1.0/24"
DOCKER_BRIDGE="172.17.0.0/16"
CROWDSEC_ENABLED="false"
API_KEY=""
TMPDIR_FL=""

log()  { printf '==> %s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<EOF
Usage: $0 [MAILCOW_ROOT] [--yes]

Installs and auto-configures FederLoom alongside the CrowdSec integration.

  MAILCOW_ROOT   Path to the Mailcow install (default: \$MAILCOW_ROOT env or
                 ${DEFAULT_MAILCOW_ROOT}).
  --yes          Accept auto-detected values without prompting. Does NOT
                 auto-join the maintainer's federation (that always prompts).
  -h, --help     Show this help.
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --yes) ASSUME_YES=1 ;;
      -h|--help) usage; exit 0 ;;
      -*) die "Unknown option: $1" ;;
      *) MAILCOW_ROOT="$1" ;;
    esac
    shift
  done
  [[ -n "$MAILCOW_ROOT" ]] || MAILCOW_ROOT="${MAILCOW_ROOT:-${DEFAULT_MAILCOW_ROOT}}"
  [[ -n "$MAILCOW_ROOT" ]] || MAILCOW_ROOT="$DEFAULT_MAILCOW_ROOT"
}

preflight() {
  [[ -d "$MAILCOW_ROOT" ]] || die "Mailcow root not found: $MAILCOW_ROOT"
  [[ -f "$MAILCOW_ROOT/docker-compose.yml" && -f "$MAILCOW_ROOT/mailcow.conf" ]] \
    || die "$MAILCOW_ROOT does not look like a Mailcow install (missing docker-compose.yml or mailcow.conf)."
  command -v docker >/dev/null 2>&1 || die "docker not found in PATH."
  command -v git >/dev/null 2>&1 || command -v curl >/dev/null 2>&1 \
    || die "need either git or curl to fetch upstream files."
  CROWDSEC_CTR="$(detect_container crowdsec || true)"
  [[ -n "$CROWDSEC_CTR" ]] \
    || die "No running CrowdSec container found. Install the CrowdSec integration first."
  log "Mailcow root : $MAILCOW_ROOT"
  log "CrowdSec ctr : $CROWDSEC_CTR"
}

detect_container() {
  # $1 = name substring; prints first matching running container name (if any)
  docker ps --format '{{.Names}}' | grep -m1 -- "$1" || true
}

extract_api_key() {
  # Reads `cscli bouncers add` output on stdin; prints the API key or nothing.
  awk 'tolower($0) ~ /api key for/ {found=1; next}
       found && /[A-Za-z0-9+\/=]{16,}/ {gsub(/[[:space:]]/,""); print; exit}'
}

generate_config() {
  # $1 = output path. Uses globals set by detect_and_confirm/register_bouncer.
  local out="$1" ip
  cat > "$out" <<EOF
# FederLoom config for this Mailcow node.
# Generated by setup-federloom.sh — do not commit (gitignored).
federation_mode: federated
store:
  dir: /var/lib/federloom
enforce:
  backend: ipset
  set_name: federloom
  chains:
    - DOCKER-USER
    - INPUT
  extra_whitelist:
EOF
  for ip in "$PUBLIC_IP" "$TAILSCALE_IP" "$MAILCOW_NETWORK" "$DOCKER_BRIDGE"; do
    [[ -n "$ip" ]] && printf '    - %s\n' "$ip" >> "$out"
  done
  cat >> "$out" <<EOF
reputation:
  block_threshold: 75
  unblock_threshold: 60
  half_life: 168h
  decay_interval: 1h
  rules_file: /etc/federloom/rules.yaml
ingest:
  mailcow_logs:
    enabled: true
    postfix_container: ${POSTFIX_CTR}
    dovecot_container: ${DOVECOT_CTR}
    poll_interval: 30s
  spamtrap:
    enabled: false
    log_file: /var/log/federloom-spamtrap.log
    poll_interval: 5s
  crowdsec:
    enabled: ${CROWDSEC_ENABLED}
    lapi_url: "http://127.0.0.1:8080"
    api_key: "${API_KEY}"
    poll_interval: 30s
    enable_decisions: true
    enable_alerts: false
observability:
  prometheus_addr: ":9101"
api:
  addr: ":9102"
  purpose: "mail"
  taxonomy:
    mail:
      - smtp-*
      - imap-*
      - pop3-*
bootstrap_peers:
  - /ip4/167.233.115.41/tcp/7700/p2p/12D3KooWBvpzbEBgcFbHrw3kEFjfdFB2AwimGMhMrVGQBHMpZNjD
dnsbl:
  addr: ":5353"
  zone: "dnsbl.federloom.mail."
EOF
}

merge_compose_file() {
  # $1 = path to docker-compose.override.yml. Idempotent; backs up before editing.
  local override="$1"
  if grep -q '# >>> federloom' "$override"; then
    log "federloom already present in $(basename "$override") — skipping merge."
    return 0
  fi
  cp "$override" "${override}.bak.$(date +%Y%m%d-%H%M%S)"

  # PUBLIC_IP is set by detect_and_confirm in a full run; defaults to 0.0.0.0 if a
  # caller invokes this standalone without detection.
  local adv="${PUBLIC_IP:-0.0.0.0}"
  local svc
  # 4-space indent for the service key, 6-space for its properties — matches the
  # existing crowdsec service block in this repo's override.
  svc=$(cat <<EOF
    # >>> federloom (added by setup-federloom.sh) >>>
    federloom:
      image: ghcr.io/joeru/federloom:latest
      container_name: federloom
      restart: unless-stopped
      cap_add: [ NET_ADMIN, NET_RAW ]
      network_mode: host
      depends_on:
        - crowdsec
      environment:
        DOCKER_HOST: unix:///host-run/docker.sock
      volumes:
        - /run:/host-run:ro
        - ./federloom/config.local.yaml:/etc/federloom/config.yaml:ro
        - ./federloom/rules.yaml:/etc/federloom/rules.yaml:ro
        - federloom-data:/var/lib/federloom
      command: >
        --config /etc/federloom/config.yaml
        --listen /ip4/0.0.0.0/tcp/7700
        --advertise /ip4/${adv}/tcp/7700
    # <<< federloom <<<
EOF
)
  local vol="    federloom-data:"

  # Insert the service after the first top-level 'services:' and the volume after
  # the first top-level 'volumes:'. If no 'volumes:' exists, append one.
  awk -v svc="$svc" -v vol="$vol" '
    { print }
    /^services:[[:space:]]*$/ && !s { print svc; s=1 }
    /^volumes:[[:space:]]*$/  && !v { print vol; v=1 }
    END { if (!v) { print "volumes:"; print vol } }
  ' "$override" > "${override}.tmp" && mv "${override}.tmp" "$override"
}

merge_compose() {
  local override="$MAILCOW_ROOT/docker-compose.override.yml"
  [[ -f "$override" ]] || die "No docker-compose.override.yml in $MAILCOW_ROOT — install the CrowdSec integration first."
  local before_bak
  before_bak="$(ls -1 "${override}".bak.* 2>/dev/null | wc -l)"
  merge_compose_file "$override"
  # Validate the merged result; restore the newest backup if it broke.
  local cfgerr
  if ! cfgerr="$( cd "$MAILCOW_ROOT" && docker compose config -q 2>&1 >/dev/null )"; then
    local newest
    newest="$(ls -1t "${override}".bak.* 2>/dev/null | head -1)"
    if [[ -n "$newest" && "$(ls -1 "${override}".bak.* 2>/dev/null | wc -l)" -gt "$before_bak" ]]; then
      cp "$newest" "$override"
      die "Merged docker-compose.override.yml failed validation — restored from $newest.
$cfgerr"
    fi
    die "docker-compose.override.yml failed validation.
$cfgerr"
  fi
  log "federloom service merged into docker-compose.override.yml."
}

extract_peer_id() {
  # Reads federloom logs on stdin; prints the last "peer ID:" value or nothing.
  grep 'peer ID:' | tail -1 | awk '{print $NF}'
}

main() {
  parse_args "$@"
  preflight
  # later tasks append: fetch_upstream; detect_and_confirm; register_bouncer;
  # generate_config; merge_compose; start_and_report; offer_federation_join
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
